global:
  scrape_interval: 2s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['13.203.103.248:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['13.203.103.248:9100']
